# Generated by Django 5.1.5 on 2025-01-30 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='نام')),
                ('l_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='شماره تلفن')),
                ('state', models.CharField(max_length=200, null=True, verbose_name='استان')),
                ('city', models.CharField(max_length=200, verbose_name='شهر')),
                ('address', models.TextField(null=True, verbose_name='آدرس')),
                ('plak', models.CharField(max_length=200, null=True, verbose_name='پلاک')),
                ('postal_code', models.CharField(max_length=200, null=True, verbose_name='کد پستی')),
                ('unit', models.CharField(max_length=200, null=True, verbose_name='واحد')),
                ('paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آبدیت شده')),
                ('total_price', models.BigIntegerField(verbose_name='قیمت')),
                ('order_code', models.CharField(max_length=100, null=True, verbose_name='شماره پیگری سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('color', models.CharField(max_length=200, verbose_name='رنگ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Products.product', verbose_name='محصولات سفارش')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created'], name='Orders_orde_created_00ebad_idx'),
        ),
    ]
