"""
Django settings for Server project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kh@^9_su89_l33i$=5wk1(0ly5%1dwa_japen5py*8oaqnvz8^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Third party lib for admin UI
    'jazzmin',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'Products.apps.ProductsConfig',
    'Accounts.apps.AccountsConfig',
    'ContactUs.apps.ContactusConfig',
    'Cart.apps.CartConfig',
    'Addreses.apps.AddresesConfig',
    'Profiles.apps.ProfilesConfig',
    'Orders.apps.OrdersConfig',
    'Home.apps.HomeConfig',
    'Payments.apps.PaymentsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = 'static/'
MEDIA_URL = 'media/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Auth User 
AUTH_USER_MODEL = "Accounts.User"

#   Zarinpal --api--merchand
# SANDBOX MODE
MERCHANT = "00000000-0000-0000-0000-000000000000"
SANDBOX = True

# Jazzmin
JAZZMIN_SETTINGS = {
    "site_title": "مدیریت سایت",  # Site title in Persian
    "site_header": "مدیریت",  # Site header in Persian
    "site_brand": "کوشان بگ",  # Site brand in Persian
    "welcome_sign": "خوش آمدید",  # Welcome sign in Persian
    "copyright": "کپی رایت",  # Copyright in Persian
    "search_model": "auth.User",  # Model to search in admin
    "show_docs": False,
    
    # Top menu settings
    "topmenu_links": [
        {"name": "داشبورد", "url": "admin:index", "permissions": ["auth.view_user"]},  # Dashboard in Persian
        {"model": "auth.User"},
        {"model": "auth.Group"},
    ],

    # Customizing the sidebar
    "user_menu": "django.contrib.auth.models.User",
    "show_sidebar": True,
    "sidebar": True,
    "sidebar_menu": [
        {"name": "داشبورد", "url": "admin:index"},  # Dashboard in Persian
        {"name": "وبلاگ‌ها", "url": "admin:Blogs_blog_changelist"},  # Blogs in Persian
        {"name": "کاربران", "url": "admin:auth_user_changelist"},  # Users in Persian
    ],

    # Theme settings
    "theme": "dark",  # Choose from 'default', 'dark', 'light', or custom themes
    "color_scheme": "default",  # You can set a color scheme here

    # Other settings
    "show_ui_builder": True,  # Show the UI builder button
    "show_settings": True,     # Show the settings button
    "show_logout": True,       # Show the logout button

    # RTL and Language settings
    "default": {
        "language": "fa",  # Set default language to Persian
        "rtl": True,       # Enable RTL layout
    },
    
    "custom_css": "css/admin.css",
    "custom_js": "js/admin.js",
}