# Generated by Django 5.1.5 on 2025-02-25 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EXP', 'منقضی شده'), ('ACT', 'فعال')], default='ACT', max_length=3, verbose_name='وضعیت')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رمز عبور یکبار مصرف',
                'verbose_name_plural': 'رمز های عبور یکبار مصرف',
            },
        ),
    ]
