# Generated by Django 5.1.5 on 2025-02-25 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EXP', 'منقضی شده'), ('ACT', 'فعال')], default='ACT', max_length=3, verbose_name='وضعیت')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رمز عبور یکبار مصرف رمز عیور',
                'verbose_name_plural': 'رمز های عبور یکبار مصرف رمز عبور',
            },
        ),
    ]
