# Generated by Django 5.1.5 on 2025-02-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_onetimepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='user',
        ),
    ]
