# Generated by Django 5.1.5 on 2025-01-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200, unique=True, verbose_name='رنگ')),
                ('available', models.BooleanField(default=True, verbose_name='موجود')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='PrimeryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='categories/', verbose_name='تصویر')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='دسته بندی اصلی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته بندی اصلی',
                'verbose_name_plural': 'دسته بندی های اصلی',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/descriptions/image/', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'توضیحات محصول',
                'verbose_name_plural': 'توضیحات محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/image/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصاویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='دسته بندی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('primery_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiled_category', to='Products.primerycategory', verbose_name='دسته بندی اصلی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('short_description', models.TextField(blank=True, help_text='مقالات، کاربرد محصول و ...', null=True, verbose_name='توضیحات مختصر محصول')),
                ('image', models.ImageField(upload_to='products/main/image/', verbose_name='تصویر اصلی محصول')),
                ('sales', models.IntegerField(default=0, verbose_name='فروش')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('str_price', models.CharField(max_length=200, verbose_name='قیمت')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد موجود محصول')),
                ('available', models.BooleanField(default=True, verbose_name='موجود')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category', verbose_name='دسته بندی محصول')),
                ('colors', models.ManyToManyField(blank=True, to='Products.color', verbose_name='رنگ های محصول')),
                ('primery_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.primerycategory', verbose_name='دسته بندی اصلی محصول')),
                ('descriptions', models.ManyToManyField(blank=True, to='Products.productdescription', verbose_name='توضیحات محصول')),
                ('images', models.ManyToManyField(blank=True, related_name='product', to='Products.productimage', verbose_name='عکس های محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['updated'],
                'indexes': [models.Index(fields=['id', 'slug'], name='Products_pr_id_c968c2_idx'), models.Index(fields=['name'], name='Products_pr_name_525943_idx'), models.Index(fields=['-created'], name='Products_pr_created_083641_idx')],
            },
        ),
    ]
