# Generated by Django 5.1.5 on 2025-01-30 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200, verbose_name='شماره تلقن')),
                ('f_name', models.CharField(max_length=200, verbose_name='نلم')),
                ('l_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('state', models.CharField(max_length=200, verbose_name='استان')),
                ('city', models.CharField(max_length=200, verbose_name='شهر')),
                ('addres', models.TextField(verbose_name='آدرس')),
                ('plak', models.CharField(max_length=200, verbose_name='پلاک')),
                ('unit', models.CharField(max_length=200, verbose_name='واحد')),
                ('postal_code', models.CharField(max_length=200, verbose_name='کد پستی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addres', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس کاربر ها',
                'verbose_name_plural': 'آدرس های کاربر ها',
            },
        ),
    ]
